INSERT INTO {SCHEMA_NAME}_ELT.{TABLE_NAME}
(	
	CREATED_BY,
	UPDATED_BY,
	CREATE_DATE,
	UPDATE_DATE,
    CUSTOMER_ID,
    PROGRAM_ID,
    LAST_PURCHASE_DATE,
    MIN_PURCHASE_DATE
)
SELECT
	'ANALYTICS_ADMIN' AS CREATED_BY,
	'ANALYTICS_ADMIN' AS UPDATED_BY,
	SYSDATE AS CREATE_DATE,
	SYSDATE AS UPDATE_DATE,
    trx.CUSTOMER_ID,
    trx.PROGRAM_ID,
    MAX(trx.TRANSACTION_DATE) AS LAST_PURCHASE_DATE,
    MIN(trx.TRANSACTION_DATE) AS MIN_PURCHASE_DATE
FROM {SCHEMA_NAME}.TRANSACTION_MAIN trx
WHERE trx.IS_DELETED = 0
AND trx.TRX_STATE_ID IN (1, 3)
GROUP BY trx.CUSTOMER_ID, trx.PROGRAM_ID
HAVING SUM(trx.AMOUNT_AFTER_DISCOUNT) > 15